name: "Bug report"
description: "Create a bug report to help us improve the game"
body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue, please do the following:
        * Search existing issues to avoid creating duplicate ones.
        * Try running a different beta branch. (in case the issue is already fixed in the future update, or to confirm it is a regression)
        * Try verifying your game file integrity in Steam before reporting an issue.
        * Please also test your issue without any addons to confirm the bug is not causing by an addon.
  - type: textarea
    id: the-report
    attributes:
      label: Details
      description: |
        Tell us exactly what happens here, every single detail that you can think of.  
        Please include information such as the console log (opened in-game by pressing SHIFT+ESC) and the version of the game you are running, which can be retrieved via the `version` console command.  

        If you are going to post crash dumps (.mdmp or .dmp files), please either send them to [robotboy655@facepunchstudios.com](mailto:robotboy655@facepunchstudios.com?subject=Bug%20Report) or upload them directly to GitHub using a `.zip` archive.
      placeholder: Describe the issue here..
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: |
        Please tell us exactly how to reproduce the issue in demand here, step by step.  
        If it is a modding API issue, please include minimal code to reproduce the issue on demand.
      placeholder: Describe how to reproduce the issue here..
    validations:
      required: true
  - type: dropdown
    id: beta
    attributes:
      label: Beta
      description: What beta version of the game are you using?
      options:
        - None/Public/Default/Main
        - Dev beta
        - x86-64 beta
      default: 0
    validations:
      required: true
